

# working in standard env
runtime: python39
service: abc

handlers:
- url: .*
  script: auto

entrypoint: gunicorn -b :$PORT main:app


## env flex not working in free tier
# runtime: python
# runtime_config:
#     operating_system: "ubuntu18"
#     runtime_version: "3.9"

# service: abcflex
# env: flex

# handlers:
# - url: /.*
#   script: auto

# entrypoint: gunicorn -b :$PORT main:app